### ISSUE TITLE
Installation broken

### ISSUE THREAD

**Issue by chemax** [joseantmazonsb/linguard#30]
Debian 10
```
└>lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
└>uname -a
Linux wginterface 4.19.0-17-amd64 #1 SMP Debian 4.19.194-2 (2021-06-21) x86_64 GNU/Linux
```

```
    If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
    
    This package requires Rust >=1.41.0.
    
    ----------------------------------------
  Can't roll back cryptography; was not uninstalled
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-jewgzdeg/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-k3nzuegy/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-jewgzdeg/cryptography/
[FATAL] Unable to install requirements.
```

also 

```
[INFO] Setting up virtual environment...
./install.sh: line 102: virtualenv: command not found
./install.sh: line 103: /var/www/linguard/venv/bin/activate: No such file or directory
```

**Comment by joseantmazonsb** [comment]
Hello there, thanks for posting the issue.

It looks like I messed up with virtual environments when I switched from `virtualenv` to `venv`. 

You should use the following:
```bash
python3 -m venv /path/to/venv/folder
```
Instead of 
```bash
virtualenv /path/to/venv/folder
```
Otherwise you'd need to install the `virtualenv` debian package.

Regarding the issue with the `criptography` module, it should be enough to add that version of Rust to the `requirements.txt` file. I intend to make a docker image as light as possible (probably using alpine as base), so I will soon be looking into what exact packages are needed for any distribution, since I am currently testing exclusively in Ubuntu 20.04.

**Comment by chemax** [comment]
Also you need install `apt-get install build-essential libssl-dev libffi-dev python-dev` for build cryptography.

**Comment by joseantmazonsb** [comment]
I think it is enough to upgrade pip, but I am still testing with a debian:buster docker image

**Comment by joseantmazonsb** [comment]
Should be fixed by now using the install script of branch #30. Let me know if you have any further problems so I can safely close this issue and merge the PR.
